name:
  Build & Deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Cars API
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: github-actions
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

