name:
  Build & Deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy Cars API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Unit Tests
        run: mvn clean package

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

